/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Singleton;

import Decorador.Audi;
import Decorador.AudiSedan;
import Decorador.Color;
import Decorador.Rines;
import Decorador.Turbo;
import Estrategia.Pagar12Meses;
import Estrategia.Pagar24Meses;
import Estrategia.Pagar36Meses;
import Estrategia.PagarContado;
import Iterador.IteraLista;
import Iterador.IteraPrecio;
import Iterador.IteraTipo;
import Iterador.Lista_Audis;
import Observador.Observable;
import Observador.Observador;
import Observador.Sujeto;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import Main.Main;

/**
 *
 * @author Ericko
 */
public class SingletonFabricaAudi extends JFrame implements Sujeto {

    Lista_Audis ls;
    IteraLista it;
    IteraPrecio itp;
    IteraTipo itt;
    AudiSedan audiA1;
    AudiSedan audiA2;
    AudiSedan audiA3;
    AudiSedan audiQ5;
    AudiSedan audiQ7;
    AudiSedan audiQ9;
    AudiSedan base;
    private static int numIns = 0;
    private static SingletonFabricaAudi instancia;
    private double total_pagar;
    private double costo_unidad, costo_decorado;
    private String nombre_base;
    private boolean turbo, color, rines;
    private ArrayList observadores;
    String componentes;

    protected SingletonFabricaAudi() {
        numIns++;
        total_pagar = 0;
        turbo = false;
        color = false;
        rines = false;
        observadores = new ArrayList();
        initComponents();
        iniciar('C');
    }

    public static SingletonFabricaAudi getInstancia() {
        if (instancia == null) {
            instancia = new SingletonFabricaAudi();
            instancia.setVisible(true);
            etiNumIns.setText("Alesco Inc ®");
            Observable gran_her = new Observable(SingletonFabricaAudi.instancia);
        }
        numIns = 0;
        return instancia;

    }

    public int getNumIns() {
        return numIns;
    }

    public void iniciar(char tipo) {
        ls = new Lista_Audis();
        itt = new IteraTipo(ls, tipo);

        audiA1 = new AudiSedan('C', "audiA1", 110000);
        audiA2 = new AudiSedan('C', "audiA2", 120000);
        audiA3 = new AudiSedan('C', "audiA3", 150000);
        audiQ5 = new AudiSedan('C', "audiQ5", 200000);
        audiQ7 = new AudiSedan('F', "audiQ7", 215000);
        audiQ9 = new AudiSedan('F', "audiQ9", 350000);

        ls.add(audiA1);
        ls.add(audiA2);
        ls.add(audiA3);
        ls.add(audiQ5);
        ls.add(audiQ7);
        ls.add(audiQ9);

        combo(ls.modelo_combo(itt));
    }

    public void reinicia(char tipo) {
        ls = new Lista_Audis();
        itt = new IteraTipo(ls, tipo);

        audiA1 = new AudiSedan('C', "audiA1", 110000);
        audiA2 = new AudiSedan('C', "audiA2", 120000);
        audiA3 = new AudiSedan('C', "audiA3", 150000);
        audiQ5 = new AudiSedan('C', "audiQ5", 200000);
        audiQ7 = new AudiSedan('F', "audiQ7", 215000);
        audiQ9 = new AudiSedan('F', "audiQ9", 350000);

        ls.add(audiA1);
        ls.add(audiA2);
        ls.add(audiA3);
        ls.add(audiQ5);
        ls.add(audiQ7);
        ls.add(audiQ9);

    }

    public void combo(DefaultComboBoxModel modelo) {
        cbxCafesBase.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo = new javax.swing.ButtonGroup();
        pago = new javax.swing.ButtonGroup();
        radCaliente = new javax.swing.JRadioButton();
        radFrio = new javax.swing.JRadioButton();
        cbxCafesBase = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        btnRines = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();
        btnTurbo = new javax.swing.JButton();
        btnAcepta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        etiNumIns = new javax.swing.JLabel();
        btnLimpia = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        etiComponentes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiPrecio_Decorado = new javax.swing.JLabel();
        mPago = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Fabricar Audi");

        Tipo.add(radCaliente);
        radCaliente.setSelected(true);
        radCaliente.setText("Sedan");
        radCaliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCalienteActionPerformed(evt);
            }
        });

        Tipo.add(radFrio);
        radFrio.setText("Camionetas");
        radFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFrioActionPerformed(evt);
            }
        });

        cbxCafesBase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCafesBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCafesBaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Auto ");

        panel.setLayout(new java.awt.GridLayout(1, 0));

        btnRines.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/rines.jpg"))); // NOI18N
        btnRines.setOpaque(false);
        btnRines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRinesActionPerformed(evt);
            }
        });
        panel.add(btnRines);
        btnRines.getAccessibleContext().setAccessibleDescription("");

        btnColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pi.eljpg.jpg"))); // NOI18N
        btnColor.setText("Panna");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        panel.add(btnColor);

        btnTurbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/turbo.png"))); // NOI18N
        btnTurbo.setText("Oreo");
        btnTurbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurboActionPerformed(evt);
            }
        });
        panel.add(btnTurbo);

        btnAcepta.setText("Facturar");
        btnAcepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        etiNumIns.setText("jLabel3");

        btnLimpia.setText("Base");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        btnCrear.setText("Fabricar");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        etiComponentes.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        etiComponentes.setText("Componentes : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Precio c/u:");

        etiPrecio_Decorado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        etiPrecio_Decorado.setText("      ");

        mPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "12 Meses", "24 Meses", "36 Meses" }));
        mPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mPagoItemStateChanged(evt);
            }
        });

        jLabel3.setText("Metodo de pago:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiNumIns))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAcepta)
                                .addGap(27, 27, 27)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radCaliente)
                                .addGap(26, 26, 26)
                                .addComponent(radFrio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxCafesBase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCrear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(etiPrecio_Decorado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiComponentes))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radCaliente)
                            .addComponent(radFrio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCafesBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpia)
                            .addComponent(btnCrear))))
                .addGap(18, 18, 18)
                .addComponent(etiNumIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiComponentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAcepta)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiPrecio_Decorado))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptaActionPerformed
       
        /*
        if (radEfectivo.isSelected()) {
            Efectivo ce = new Efectivo(costo_decorado);
            ce.mostrar_pago();
        } else {
            Tarjetas ct = new Tarjetas(costo_decorado);
            ct.mostrar_pago();
        }
        */
        // DESTRUYE SINGLETON
        Main.areaInforme.setText(null);
        Main.abierta_cc = false;
        this.instancia.dispose();
        this.instancia = null;
    }//GEN-LAST:event_btnAceptaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // DESTRUYE SINGLETON
        Main.areaInforme.setText(null);
        Main.abierta_cc = false;
        this.instancia.dispose();
        this.instancia = null;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void radFrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFrioActionPerformed
        iniciar('F');
    }//GEN-LAST:event_radFrioActionPerformed

    private void radCalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCalienteActionPerformed
        iniciar('C');
    }//GEN-LAST:event_radCalienteActionPerformed

    private void btnTurboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnturboActionPerformed
        turbo = true;
        btnTurbo.setEnabled(false);
    }//GEN-LAST:event_btnturboActionPerformed

    private void btnRinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrinesActionPerformed
        rines = true;
        btnRines.setEnabled(false);
    }//GEN-LAST:event_btnrinesActionPerformed

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolorActionPerformed
        color = true;
        btnColor.setEnabled(false);
    }//GEN-LAST:event_btncolorActionPerformed

    private void cbxCafesBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCafesBaseActionPerformed
        // Se establece el cafe elegido pibe
        if (radCaliente.isSelected()) {
            reinicia('C');
        } else {
            reinicia('F');
        }

        String nombre_cafe = cbxCafesBase.getSelectedItem().toString(); // Obtengo el cafe base
        base = ls.get_elegido(nombre_cafe, itt);
    }//GEN-LAST:event_cbxCafesBaseActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // Este boton crearar los cafes con todos los componentes extras seleccionados
        // Existen 7 combinaciones posibles creo xD
        // Cafes con un ingrediente extra

         componentes = "Componentes: ";

        if (color == true && turbo == false && rines == false) {
            Audi audi_o = new Color(base);
            componentes += audi_o.componentes();
            costo_decorado = audi_o.precio();
        }
        if (rines == true && color == false && turbo == false) {
            Audi audi_r = new Rines(base);
            System.out.println(audi_r.componentes());
            componentes += audi_r.componentes();
            costo_decorado = audi_r.precio();
        }
        if (turbo == true && rines == false && color == false) {
            Audi audi_t = new Turbo(base);
            System.out.println(audi_t.componentes());
            componentes += audi_t.componentes();
            costo_decorado = audi_t.precio();
        }
        // Cafe con todos los componentes extras
        if (color == true && turbo == true && rines == true) {
            Audi audi_todos = new Color(new Turbo(new Rines(base)));
            System.out.println(audi_todos.componentes());
            componentes += audi_todos.componentes();
            costo_decorado = audi_todos.precio();
        }
        // Cafe con color y turbo
        if (color == true && turbo == true && rines == false) {
            Audi audi_oc = new Color(new Turbo(base));
            componentes += audi_oc.componentes();
            costo_decorado = audi_oc.precio();
        }
        // Cafe con color y rines
        if (color == true && rines == true && turbo == false) {
            Audi audi_op = new Color(new Rines(base));
            componentes += audi_op.componentes();
            costo_decorado = audi_op.precio();
        }
        // Cafe con turbo y rines
        if (turbo == true && rines == true && color == false) {
            Audi audi_cp = new Turbo(new Rines(base));
            componentes += audi_cp.componentes();
            costo_decorado = audi_cp.precio();
        }

        // Cafe sin nada pff
        if (turbo == false && rines == false && color == false) {
            Audi audisedan = base;
            componentes += audisedan.componentes();
            costo_decorado = audisedan.precio();
        }

        etiComponentes.setText(componentes);
        etiPrecio_Decorado.setText("$ " + costo_decorado);
        //txtTotalPagar.setText("$ " + costo_decorado * obtenCantidad());
        total_pagar = costo_decorado;

        cambiosMedicion();

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        color = false;
        turbo = false;
        rines = false;

        btnTurbo.setEnabled(true);
        btnColor.setEnabled(true);
        btnRines.setEnabled(true);
        etiComponentes.setText(base.componentes());
        etiPrecio_Decorado.setText("$ " + base.getPrecio());
        costo_decorado = base.getPrecio();
        //txtTotalPagar.setText("$ " + costo_decorado * obtenCantidad());
        total_pagar = costo_decorado;
        cambiosMedicion();
    }//GEN-LAST:event_btnLimpiaActionPerformed

    private void mPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mPagoItemStateChanged
        switch((String)mPago.getSelectedItem()){
            case "Contado": 
                            this.etiPrecio_Decorado.setText(""+
                            new PagarContado(costo_decorado).calcularPagos());
                            break;
            case "12 Meses":       
                            this.etiPrecio_Decorado.setText(""+
                            new Pagar12Meses(costo_decorado).calcularPagos());
                            break;
            case "24 Meses":       
                            this.etiPrecio_Decorado.setText(""+
                            new Pagar24Meses(costo_decorado).calcularPagos());
                            break;
            case "36 Meses":       
                            this.etiPrecio_Decorado.setText(""+
                            new Pagar36Meses(costo_decorado).calcularPagos());
                            break;
        }
    }//GEN-LAST:event_mPagoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JButton btnAcepta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JButton btnRines;
    private javax.swing.JButton btnTurbo;
    private javax.swing.JComboBox cbxCafesBase;
    private javax.swing.JLabel etiComponentes;
    public static javax.swing.JLabel etiNumIns;
    private javax.swing.JLabel etiPrecio_Decorado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> mPago;
    private javax.swing.ButtonGroup pago;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton radCaliente;
    private javax.swing.JRadioButton radFrio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void remueveObservador(Observador o) {
        int i = observadores.indexOf(o);
        if (i >= 0) {
            observadores.remove(o);
        }
    }

    @Override
    public void notificaObservadores() {
        for (int i = 0; i < observadores.size(); i++) {
            Observador observador = (Observador) observadores.get(i);
            //(float costo_total,float costo_unitario,int cantidad, String nombre);
            observador.actualiza(total_pagar, costo_decorado, 1, etiComponentes.getText());
        }
    }
    @Override
    public void registraObservador(Observador o) {
        observadores.add(o);
    }

    public void cambiosMedicion() {
        notificaObservadores(); /// cambio de estado modificacion en el estado
    }
}
